### ISSUE TITLE
Allow publishing into a separate directory

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash-CLI#4]
It would be nice if I could publish to a separate directory so I can be sure I have no unneeded junk like I might have in my project folder.

**Comment by wozniakty** [comment]
Somehow I swore this didn't work.  Nvm

**Comment by wozniakty** [comment]
So this seems to be intended to work, but the zip that was produced didn't work.
Issues:
- Zip contained folder for C_ and Repos (the parent folders of my project)
- Zip did not contain the Content.yml file

**Comment by dislogical** [comment]
1) The zip containing other folders is a problem, I'll look into that.
2) Zip does not need the Content.yml file. It should be embedded in the exe, assuming you have your `dub.json` setup properly.

**EDIT:** Your `dub.json` needs [this](https://github.com/Circular-Studios/Dash-CLI/blob/57fd8ee9ebfb631cef4c39a9487e5e69dea17287/empty-game/dub.json#L33-L39).

**Comment by dislogical** [comment]
Fixed the folder path thing in 19fe313faeaadc72ff53baeb237753c3c01274b6.
