### ISSUE TITLE
Cannot open "create"

### ISSUE THREAD

**Issue by MggMuggins** [Circular-Studios/Dash-CLI#7]
I installed the dash cli according to [these](http://dash.circularstudios.com/guides/gettingstarted.html) instructions (Linux), but I'm getting this error:
```sh
dash: 0: Can't open create
```
Anyone have any insight on this?

**Comment by brooklynlittell** [comment]
My quick guess is that the included `empty-game.zip` is severely out of date. Pinging @ColdenCullen in case he has more insight.

**Comment by dislogical** [comment]
Hmm, my guess is you have another tool called "dash" that's hijacking the command. If you run `which dash`, do you get the dash cli? If not, you may need to specify the full path to the dash cli exe.

**Comment by MggMuggins** [comment]
That was exactly it. I renamed the binary a bit so that it's more convenient. Thanks a lot!
(Also on Linux, but that's a tiny detail...)
